name: Release npm package

on:
  push:
    branches:
      #- master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: 'node:lts-buster'
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - run: npm run ts:types
      - run: npm run tsc:build
      #- run: npm run semantic:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
